# This workflow will build a docker container, publish it to Azure Container Registry, and deploy it to Azure Kubernetes Service using a helm chart.
#
# To configure this workflow:
#
# 1. Set up the following secrets in your workspace: 
#     a. REGISTRY_USERNAME with ACR username
#     b. REGISTRY_PASSWORD with ACR Password
#     c. AZURE_CREDENTIALS with the output of `az ad sp create-for-rbac --sdk-auth`
#
# 2. Change the values for the REGISTRY_NAME, CLUSTER_NAME, CLUSTER_RESOURCE_GROUP and NAMESPACE environment variables (below).

on: [push]

# Environment variables available to all jobs and steps in this workflow
env:
  REGISTRY_NAME: acrhackfestjpk13013
  CLUSTER_NAME: aksjpk13013
  CLUSTER_RESOURCE_GROUP: aks-rg-jpk13013
  NAMESPACE: hackfest
  IMAGETAG: githubbuild-${{github.run_id}}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - name: Azure Login
      uses: Azure/login@v1
      with:
         # Paste output of `az ad sp create-for-rbac` as value of secret variable: AZURE_CREDENTIALS
        creds: '${{ secrets.AZURE_CREDENTIALS }}'
    
#     - name: Build ACR images
#       uses: Azure/cli@v1.0.0
#       with:
#         # Specify the script here
#         inlineScript: |
          
#           az acr build -t hackfest/data-api:${{ env.IMAGETAG }} -r ${{ env.REGISTRY_NAME }} --no-logs ./app/data-api 
#           az acr build -t hackfest/flights-api:${{ env.IMAGETAG }} -r ${{ env.REGISTRY_NAME }} --no-logs ./app/flights-api
#           az acr build -t hackfest/quakes-api:${{ env.IMAGETAG }} -r ${{ env.REGISTRY_NAME }} --no-logs ./app/quakes-api
#           az acr build -t hackfest/weather-api:${{ env.IMAGETAG }} -r ${{ env.REGISTRY_NAME }} --no-logs ./app/weather-api
#           az acr build -t hackfest/service-tracker-ui:${{ env.IMAGETAG }} -r ${{ env.REGISTRY_NAME }} --no-logs ./app/service-tracker-ui 

    - name: Helm tool installer
      uses: Azure/setup-helm@v1
      with:
        # Version of helm
        version: v3.1.1
        
        
    - name: Helm Upgrade
      uses: Azure/cli@v1.0.0
      with:
        # Specify the script here
        inlineScript: |

          /opt/hostedtoolcache/helm/3.1.1/x64/linux-amd64/helm upgrade --install data-api charts/data-api --namespace hackfest
          helm upgrade --install quakes-api charts/quakes-api --namespace hackfest
          helm upgrade --install weather-api charts/weather-api --namespace hackfest
          helm upgrade --install flights-api charts/flights-api --namespace hackfest
          helm upgrade --install service-tracker-ui charts/service-tracker-ui --namespace hackfest
      
